### PR TITLE
Do not double-call prevPage and nextPage callback

### PR DESCRIPTION
**Pull request by singlow**
When I use ListIterator.nextPage and pass in a callback, it is passing the callback to the load function, which will call the callback async, and then the nextPage function calls the callback itself, synchronously. This second call will actually contain the Results from the first page, since load has not yet run. prevPage looks like it does the same thing.

I built my code to recursively call nextPage until it is done to download an entire list, however the result is that a 10 page list results in my callback getting called 10 + 9 + 8 + 7... times. Is there another way this is supposed to be used?

This Gist has a sample of how I am trying to use it:
https://gist.github.com/singlow/5008826

Additionally, right now Twilios paging parameters seem to be non-functional for the Accounts list so it is pointless to really test it. Their support team said they are working on that. 

Looks like paging works on non-Accounts lists so I may post an updated gist soon that can be properly tested.

### CODE REVIEW

**Comment by bminer** [comment]
Thanks for the pull request.  Your patch is a minimal change and definitely fixes a bug.  The callback should only be called once, as you mentioned.

To answer your question, the best way to download the entire N page list is to call your function recursively as you are doing.  This should only call your callback 10 times, though...  Not 10 + 9 + 8 + ....  right?  That is... assuming this fix is put into place...

**Comment by bminer** [comment]
@singlow - If the user tries to call prevPage() and you are on page 1, the `cb` should be called with an Error passed as the first argument.  That's the only other change I would make.  Same goes for nextPage()... throw an Error if they exceed the total number of pages.  Would you be willing to make this change, add yourself to the list of contributors (in package.json) and push the version number to 0.3.2?

Thanks again for bringing this issue to my attention!

**Comment by singlow** [comment]
OK. I updated the branch with the changes you requested.

**Comment by bminer** [comment]
Thanks!  Merging now...

**Pull request merged**
